name: Generate docs

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docs:
          # { ref: <branch/tag name>, name: <docs drop down entry> }
          - { ref: main, name: latest }
          - { ref: v0.2.1, name: 0.2.1 }
          - { ref: v0.2.3, name: 0.2.3 }
          - { ref: v0.2.4, name: 0.2.4 }
          - { ref: v0.3.0, name: 0.3.0 }
    steps:
      - uses: actions/checkout@v5
        if: ${{ matrix.docs.ref == 'main' }}
      - uses: actions/checkout@v5
        with:
          ref: ${{ matrix.docs.ref }}
        if: ${{ matrix.docs.ref != 'main' }}

      - uses: bazelbuild/setup-bazelisk@v3

      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Generate docs
        run: bash ./build-docs.sh
        env:
          CI: 1
        working-directory: ${{ github.workspace }}/docs

      - run: bazelisk shutdown

      - uses: actions/upload-artifact@v6
        with:
          name: "${{ matrix.docs.name }}"
          path: ${{ github.workspace }}/docs/site/
          if-no-files-found: error
        if: ${{ github.event_name != 'pull_request' }}

  publish:
    needs: pages
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/download-artifact@v7
        with:
          path: ${{ github.workspace }}/docs/generated
      - name: Inspect docs site directory structure
        run: find ${{ github.workspace }}/docs/generated -maxdepth 2

      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - run: |
          pip install packaging==23.*
          python versioning.py generated/
        working-directory: ${{ github.workspace }}/docs

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/generated
          force_orphan: true
